# Numpy


NumPy ( Numerical Python ) es una biblioteca Python de código abierto que se utiliza en casi todos los campos de la ciencia y la ingeniería. Es el estándar universal para trabajar con datos numéricos en Python y es el núcleo de los ecosistemas científicos de Python y PyData. 

Proporciona ndarray (numpy dimenional array), un objeto de matriz n-dimensional homogéneo, con métodos para operar de manera eficiente en él. 



## Instalando Numpy
Generalmente cuando trabajamos con Numpy se suele usar con una distribución científica de Python como lo es el Anaconda y su instalación bien sea dentro de dicha distribución científica o no puede hacerse de la siguiente forma:
Podemos usar el manejador de paquetes de Python dentro del terminal:


In [ ]:
#%pip install numpy
#%conda install numpy


## Importar Numpy

In [2]:
import numpy as np

## Creando Arrays con Numpy
En particular, un array de Numpy pueden ser creados dentro de Python a través de una lista o de una tupla empleando em método .array()



In [2]:
#Via Lista
lista1 = [1, 2, 3, 4]
array1 = np.array(lista1)
print(array1)

#Via tupla
array2 = np.array( (5, 8, 9, 4) )
print(array2)

#tipo ndarray
print(type(array1))


[1 2 3 4]
[5 8 9 4]
<class 'numpy.ndarray'>


Numpy posee algunos métodos que permiten la creación rápida de arreglos con determinados elementos.

* np.zeros(2): Arreglo lleno de ceros
* np.ones(2): Arreglo lleno de unos
* np.empty(2): crea una matriz cuyo contenido inicial es aleatorio y depende del estado de la memoria. 
* np.arange(4): crea una matriz con un rango de elementos


In [4]:
#try here
azeros = np.zeros(10)
print('Array Zeros', azeros)

aones = np.ones(5) * 15
print('Array Ones', aones)

aempty = np.empty(6)
print('Array Empty', aempty)

aran = np.arange(5)
print('Array Range', aran)


Array Zeros [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
Array Ones [15. 15. 15. 15. 15.]
Array Empty [0. 0. 0. 0. 0. 0.]
Array Range [0 1 2 3 4]


Arreglo con un rango de intervalos espaciados uniformemente. Para hacer esto se debe colocar el primer número , el último número y el tamaño del paso .
* np.arange(2, 9, 2)


In [5]:
#code
aran = np.arange(15, 40, 3)
print(aran)

[15 18 21 24 27 30 33 36 39]


para crear una matriz con valores que están espaciados linealmente en un intervalo específico:
* np.linspace(0, 10, num=5)


In [8]:
#code
alin = np.linspace(0, 10, num=4)
print(alin)

[ 0.          3.33333333  6.66666667 10.        ]


## Dimensionalidad de los Arrays
Numpy tiene varios métodos que nos permiten determinar la forma y el tamaño de un arreglo o una matriz.

* *ndarray.ndim* muestra el número de ejes, o dimensiones, de la matriz.
* *ndarray.size* muestra el número total de elementos de la matriz. Este es el producto de los elementos de la forma de la matriz.
* *ndarray.shape* mostrará una tupla de enteros que indican el número de elementos almacenados a lo largo de cada dimensión de la matriz. Si, por ejemplo, tiene una matriz 2-D con 2 filas y 3 columnas, la forma de su matriz es (2, 3)


In [12]:
aempty

array([0., 0., 0., 0., 0., 0.])

In [9]:
#code
print('Dimension', array1.ndim)
print('Size', aones.size)
print('Shape', aempty.shape)


Dimension 1
Size 5
Shape (6,)


En este contexto, note que con Numpy podemos crear múltiples dimensiones (profundidad) de arreglos respetando siempre que cada una de las dimensiones los arreglos estén conformados por el mismo número de elementos.

* **Arreglo 0-dimensional:** Pueden ser considerados como una constante o escalar.


In [13]:
#code
a0 = np.array(15)
print('Array 0-dimensional: ', a0.ndim)


Array 0-dimensional:  0


**Arreglo 1-dimensional:** Arreglos con un único nivel de profundidad.


In [14]:
#code
a1 = np.array([1,2,5])
print(a1)
print('Array 1-dimensional: ', a1.ndim)

[1 2 5]
Array 1-dimensional:  1


**Arreglo 2-dimensional:** Arreglos que contienen otros arreglos unidimensionales. Cada dimension debe respetar el la cantidad de elementos para evitar tener un error


In [17]:
#code
a2 = np.array( [ [1, 2], [3, 4] ] )
print(a2)
print('Array 2-dimensional: ', a2.ndim)

a2wrong = np.array( [ [1, 2, 8], [3, 4, 6] ] )
print(a2wrong)
print('Array Shape Wrong: ', a2wrong.shape)

[[1 2]
 [3 4]]
Array 2-dimensional:  2
[[1 2 8]
 [3 4 6]]
Array Shape Wrong:  (2, 3)


**Arreglo 3-dimensional:** Arreglos que contienen otros arreglos bidimensionales. Importante respetar el Shape


In [19]:
#code
a3 = np.array( [ [ [1, 2], [3, 4] ], [ [1, 2], [3, 4] ] ] )
print(a3)
print('Array 3-dimensional: ', a3.ndim)
print('Array Shape: ', a3.shape)

[[[1 2]
  [3 4]]

 [[1 2]
  [3 4]]]
Array 3-dimensional:  3
Array Shape:  (2, 2, 2)


**Arreglo multi-dimensional:** Arreglos que contienen un número finito de dimensiones.


In [21]:
am = np.array( [1, 5, 4], ndmin=10 )
print(am)
print('Array multi-dimensional: ', am.ndim)
print('Array Shape: ', am.shape)


[[[[[[[[[[1 5 4]]]]]]]]]]
Array multi-dimensional:  10
Array Shape:  (1, 1, 1, 1, 1, 1, 1, 1, 1, 3)


## Remodelar un Arreglo
El uso del método arr.reshape() permite darle una nueva forma a una matriz sin cambiar los datos. 

Se debe respetar que la matriz que se desea producir debe tener la misma cantidad de elementos que la matriz original. Si comienza con una matriz con 12 elementos, deberá asegurarse de que su nueva matriz también tenga un total de 12 elementos.


In [27]:
#code
a = np.arange(6)
print('Arreglo Inicial: \n', a)
b = a.reshape(3, 2)
print('Arreglo Remodelado: \n', b)
c = a.reshape(3, 1, 2)
print('Arreglo Remodelado en Más Dimensiones: \n', c)


Arreglo Inicial: 
 [0 1 2 3 4 5]
Arreglo Remodelado: 
 [[0 1]
 [2 3]
 [4 5]]
Arreglo Remodelado en Más Dimensiones: 
 [[[0 1]]

 [[2 3]]

 [[4 5]]]


## Elementos de un Array
Veremos a continuación como acceder a los datos de los arreglos creados con Numpy:

**Arreglo Unidimensional:** Básicamente es igual que las listas, se accede a través de corchetes especificando el índice que se desea.


In [ ]:
#Code
array1 = np.array([1, 2, 3, 4])
print(array1)
print()
print()


**Arreglo Multidimensional:** Se tiene que especificar el índice del elemento ubicado en la dimensión **menos profunda** hasta llegar al índice del elemento indicado que se encuentra en la dimensión **más profunda** todos dentro de un corchete separados por comas.


In [ ]:
a2 = np.array( [ [1, 2], [3, 4] ] )
print(a2)
print('(0, 1): ', )
print('(1, 0): ', )


In [ ]:
#Code Tridimensional
a3 = np.array([ [ [1, 2, 3], [4, 5, 6] ], [ [7, 8, 9], [-1, -2, -3] ] ])
print(a3)
print('escalar 1: ', )
print('escalar 2: ', )
print('escalar 3: ', )
print('intercalado: ', )
print('vector: \n', )
print('matriz: \n', )

También es posible extraer de los arrays aquellos elementos que satisfagan una determinada condición lógica. Por ejemplo:


In [29]:
a = np.array([[1 , 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])
print('Arreglo: \n', a)
print('a < 6 = ', a[ a < 6 ])

Arreglo: 
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
a < 6 =  [1 2 3 4 5]


También podemos indexar un nuevo array con estos condicionales

In [ ]:
b = 0
print('Nuevo arreglo con a >= 5: \n', b)

También se puede aplicar alguna determinada operación para la creación de un nuevo array.


In [30]:
c = a[ a%2 == 0 ]
print('Nuevo arreglo par: \n', c)

Nuevo arreglo par: 
 [ 2  4  6  8 10 12]


También puede hacer uso de los operadores lógicos & y | para devolver valores booleanos que especifican si los valores en una matriz cumplen o no una determinada condición. Esto puede ser útil con arreglos que contienen nombres u otros valores categóricos.


In [31]:
b = ( a > 5) | (a == 5)
print('Arreglo Booleano que Cumple la Condición: \n', b)


Arreglo Booleano que Cumple la Condición: 
 [[False False False False]
 [ True  True  True  True]
 [ True  True  True  True]]


In [32]:
c = a[b]
print(c)

[ 5  6  7  8  9 10 11 12]


## Operaciones Básicas
La clase array permite realizar varias operaciones matemáticas de forma muy sencilla, sin embargo esta biblioteca generalmente es empleada para operar con matrices por lo que realizar operaciones de suma y resta implica que los arrays creados tengan la misma forma.


In [34]:
a1 = np.array([1, 2, 3, 4, 5])
a2 = np.array([6, 7, 8, 9, 10])
#Suma
a1 + a2

array([ 7,  9, 11, 13, 15])

In [35]:
#resta
a1-a2

array([-5, -5, -5, -5, -5])

El producto, la división y la potencia necesitan que el número de columnas del primer array coincida con el número de filas del segundo array.


In [36]:
#Multiplicación
a1 * a2



array([ 6, 14, 24, 36, 50])

In [37]:
#División
a1 / a2


array([0.16666667, 0.28571429, 0.375     , 0.44444444, 0.5       ])

In [38]:
#Potencia
a1 ** a2


array([      1,     128,    6561,  262144, 9765625])

## Tipos de Datos

En Numpy encontramos tipos de datos adicionales
* i: integer
* u: unsigned integer
* f: float
* c: complex float
* b: boolean
* m: timedelta (valores de tiempo)
* M: datetime (fecha y hora)
* O: object 
* S: string
* U: unicode string
* V: void


In [40]:
a = np.array([1, 2, 3, 4, 5])
print(a)
a.dtype



[1 2 3 4 5]


dtype('int32')

In [43]:
b = np.array([True, False, 8.0])
b.dtype

dtype('float64')

## Clonado de Arrays
Al igual que con las listas, para compiar un arrego debemos emplear el método .copy() porque de lo contrario estaremos cayendo en los errores de codificación conocidos como los Side Effects.
Los se encuentran referenciados en la memoria por lo tanto cuando trabajamos con subarrays todos los cambios que hagamos se verán reflejados en el array original. 


In [49]:
a3 = np.arange(10, 80, 10)
print(a3)

[10 20 30 40 50 60 70]


In [50]:
sub_a3 = a3[:5].copy()
sub_a3

array([10, 20, 30, 40, 50])

In [51]:
sub_a3 *= 2
sub_a3

array([ 20,  40,  60,  80, 100])

In [52]:
print(a3)

[10 20 30 40 50 60 70]


Al igual que con las listas, para copiar un arreglo debemos emplear el método .copy() porque de lo contrario estaremos cayendo en los errores de codificación conocidos como los Side Effects

In [54]:
a = np.arange(6)
c = a.copy()
print(id(a))
print(id(c))


1466889076624
1466889406192


## Recorriendo Arreglos
Al igual que las listas la mejor forma para recorrer un arreglo es empleando el ciclo FOR.


In [5]:
# array 1D
d1 = np.array([1.5, 'b', True, 4])
for i in d1:
    print(i)


1.5
b
True
4


In [10]:
# array 2D
d2 = np.array([[1.5, 'b', True, 4], range(4)])
#print(d2)
for i in d2:
    print(i)


['1.5' 'b' 'True' '4']
['0' '1' '2' '3']


In [11]:
for d1 in d2:
    for i in d1:
        print(i)

1.5
b
True
4
0
1
2
3


In [ ]:
# array 3D
d2 = np.array([[1.5, 'b', True, 4], range(4)])


Al igual que las listas la mejor forma para recorrer un arreglo es empleando el ciclo FOR.


In [13]:
d3 = np.array([[range(3),range(3,6),range(6,9)]])
for d2 in d3:
    print(d2)


[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [14]:
d3 = np.array([[range(3),range(3,6),range(6,9)]])
for d2 in d3:
    for d1 in d2:
        print(d1)


[0 1 2]
[3 4 5]
[6 7 8]


In [15]:
d3 = np.array([[range(3),range(3,6),range(6,9)]])
for d2 in d3:
    for d1 in d2:
        for i in d1:
            print(i)


0
1
2
3
4
5
6
7
8


Se puede hacer un reshape de un arreglo multidimensional a un arreglo unidimensional, sin embargo esto es solo recomendable si el arreglo NO posee una dimensión elevada.


In [16]:
# Array 3D
print(d3)


[[[0 1 2]
  [3 4 5]
  [6 7 8]]]


In [17]:
for i in d3.reshape(-1):
    print(i)

0
1
2
3
4
5
6
7
8


Una manera más eficiente de hacer esto es emplear el método .nditer() que crea un iterable el cual permite imprimir todos los elementos de los arrays 1D


In [18]:
#code
for i in np.nditer(d3):
    print(i)


0
1
2
3
4
5
6
7
8


## Concatenar Arrays
La forma de concatenar dos o más arrays es empleando el método .concatenate()


In [19]:
#code
a1 = np.array([1, 2, 3, 4, 5])
a2 = np.array([6, 7, 8, 9, 10])
a3 = np.concatenate( (a1, a2) )
print(a3)


[ 1  2  3  4  5  6  7  8  9 10]


Para el caso bidimensional puedo seleccionar si desea hacer la concatenación de forma vertical o horizontal colocando el atributo axis


In [20]:
b1 = np.array([[-3, -2.5], [-2, -1.5], [-1, -0.5]])
b2 = np.array([[0.5, 1], [1.5, 2], [2.5, 3]])
print('b1 = ', b1)
print('b2 = ', b2)

b1 =  [[-3.  -2.5]
 [-2.  -1.5]
 [-1.  -0.5]]
b2 =  [[0.5 1. ]
 [1.5 2. ]
 [2.5 3. ]]


In [21]:
#axis0 (Concatenación Vertical)
b3 = np.concatenate( (b1, b2), axis = 0 )
print('b3 = ', b3)


b3 =  [[-3.  -2.5]
 [-2.  -1.5]
 [-1.  -0.5]
 [ 0.5  1. ]
 [ 1.5  2. ]
 [ 2.5  3. ]]


In [22]:
#axis1 (Concatenación Horizontal)
b4 = np.concatenate( (b1, b2), axis = 1 )
print('b4 = ', b4)


b4 =  [[-3.  -2.5  0.5  1. ]
 [-2.  -1.5  1.5  2. ]
 [-1.  -0.5  2.5  3. ]]


In [23]:
#Arrays para Concatenar
c1 = np.array([[[-10, -9], [-8, -7], [-6, -5]], [[-4, -3], [-2, -1], [0, 0]]])
c2 = np.array([[[0, 0], [1, 2], [3, 4]], [[5, 6], [7, 8], [9, 10]]])
print('c1 = \n', c1)
print('c2 = \n', c2)


c1 = 
 [[[-10  -9]
  [ -8  -7]
  [ -6  -5]]

 [[ -4  -3]
  [ -2  -1]
  [  0   0]]]
c2 = 
 [[[ 0  0]
  [ 1  2]
  [ 3  4]]

 [[ 5  6]
  [ 7  8]
  [ 9 10]]]


Concatenar en la primera dimensión (Concatena los dos arrays bidimensionales)


In [24]:
c3 = np.concatenate((c1, c2), axis = 0)
print('c3 = \n', c3)

c3 = 
 [[[-10  -9]
  [ -8  -7]
  [ -6  -5]]

 [[ -4  -3]
  [ -2  -1]
  [  0   0]]

 [[  0   0]
  [  1   2]
  [  3   4]]

 [[  5   6]
  [  7   8]
  [  9  10]]]


Concatenar en la segunda dimensión (Concatena los dos arrays unidimensionales en vertical)


In [25]:
c3 = np.concatenate((c1, c2), axis = 1)
print('c3 = \n', c3)

c3 = 
 [[[-10  -9]
  [ -8  -7]
  [ -6  -5]
  [  0   0]
  [  1   2]
  [  3   4]]

 [[ -4  -3]
  [ -2  -1]
  [  0   0]
  [  5   6]
  [  7   8]
  [  9  10]]]


Concatenar en la segunda dimensión (Concatena los dos arrays unidimensionales en horizontal)


In [26]:
c3 = np.concatenate((c1, c2), axis = 2)
print('c3 = \n', c3)

c3 = 
 [[[-10  -9   0   0]
  [ -8  -7   1   2]
  [ -6  -5   3   4]]

 [[ -4  -3   5   6]
  [ -2  -1   7   8]
  [  0   0   9  10]]]


Otra forma de concatenar arreglos es empleando el método .stack() (apilar) con la diferencia que esta concatenación se hace sobre un eje nuevo.


In [27]:
a1 = np.array([1, 2, 3])
a2 = np.array([7, 8, 9])
print('a1 = \n', a1)
print('a2 = \n', a2)

a1 = 
 [1 2 3]
a2 = 
 [7 8 9]


In [28]:
#axis0
a = np.stack( (a1, a2), axis=0 )
print(a)


[[1 2 3]
 [7 8 9]]


In [29]:
#axis1
a = a = np.stack( (a1, a2), axis=1 )
print(a)

[[1 7]
 [2 8]
 [3 9]]


Numpy proporciona un helper hstack() para hacer una concatenación por filas, el helper vstack() lo hace por columnas y un helper dstack() para hacer una concatenación por profundidad


In [30]:
a1 = np.array([-3, -2, -1])
a2 = np.array([1, 2, 3])
print('a1 = \n', a1)
print('a2 = \n', a2)

a1 = 
 [-3 -2 -1]
a2 = 
 [1 2 3]


In [31]:
#hstack
a = np.hstack( (a1, a2))
print(a)


[-3 -2 -1  1  2  3]


In [32]:
#vstack
a = np.vstack( (a1, a2))
print(a)


[[-3 -2 -1]
 [ 1  2  3]]


In [33]:
#dstack
a = np.dstack( (a1, a2))
print(a)


[[[-3  1]
  [-2  2]
  [-1  3]]]


Array 2D

In [34]:
b1 = np.array([[-6, -5], [-4, -3], [-2, -1]])
b2 = np.array([[1, 2], [3, 4], [5, 6]])
print('b1 = \n', b1)
print('b2 = \n', b2)

b1 = 
 [[-6 -5]
 [-4 -3]
 [-2 -1]]
b2 = 
 [[1 2]
 [3 4]
 [5 6]]


In [35]:
#hstack
b = np.hstack( (b1, b2) )
print(b)


[[-6 -5  1  2]
 [-4 -3  3  4]
 [-2 -1  5  6]]


In [36]:
#vstack
b = np.vstack( (b1, b2) )
print(b)


[[-6 -5]
 [-4 -3]
 [-2 -1]
 [ 1  2]
 [ 3  4]
 [ 5  6]]


In [37]:
#dstack
b = np.dstack( (b1, b2) )
print(b)


[[[-6  1]
  [-5  2]]

 [[-4  3]
  [-3  4]]

 [[-2  5]
  [-1  6]]]


Array 3D

In [ ]:
c1 = np.array([[[-10, -9], [-8, -7], [-6, -5]], [[-4, -3], [-2, -1], [0, 0]]])
c2 = np.array([[[0, 0], [1, 2], [3, 4]], [[5, 6], [7, 8], [9, 10]]])
print('c1 = \n', c1)
print('c2 = \n', c2)

In [ ]:
#hstack
c = 0
print(c)


In [ ]:
#vstack
c = 0
print(c)


In [ ]:
#dstack
c = 0
print(c)


## División de Arrays
El proceso inverso a la concatenación es la división de arrays. La división de arrays consiste en romper un array en múltiples arrays.

**.array_split(array, division)** divide un array y lo almacena en una lista


In [39]:
x = np.array([1, 2, 3, 4, 5, 6, 7, 8])
print(x)

[1 2 3 4 5 6 7 8]


In [45]:
#split
y = np.array_split(x, 4)
print("Array x =", x)
print("Array y:", y)


Array x = [1 2 3 4 5 6 7 8]
Array y: [array([1, 2]), array([3, 4]), array([5, 6]), array([7, 8])]


Numpy proporciona un helper hsplit() para dividir un array por filas, el helper vsplit () lo hace por columnas y el helper dsplit () lo hace por profundidad


In [46]:
#horizontal split
h_arr = np.hsplit(x, 4)
print('Horizontal split', h_arr)

Horizontal split [array([1, 2]), array([3, 4]), array([5, 6]), array([7, 8])]


In [48]:
#vertical split (solo para arreglos de 2 o más dimensiones)
arr2d = np.array([[2, 4, 6], [1, 3, 5], [7, 11, 10]])
v_arr = np.vsplit(arr2d, 3)
print('Bi dimensional matriz\n',arr2d)
print('Horizontal split', v_arr)

Bi dimensional matriz
 [[ 2  4  6]
 [ 1  3  5]
 [ 7 11 10]]
Horizontal split [array([[2, 4, 6]]), array([[1, 3, 5]]), array([[ 7, 11, 10]])]


## Arrays Transpuestos

Ya hemos observado que con NumPy podemos trabajar fácilmente con cálculo matricial, en este mismo campo, vamos a aprender como transponer arreglos y matrices.
La traspuesta $𝑨^𝑇$ de una matriz 𝑨 puede ser obtenida reflejando los elementos a lo largo de su diagonal


In [50]:
q1 = np.array([[1,2,3],[4,5,6]])
print(q1)
# Tranpuesta
print(q1.T)


[[1 2 3]
 [4 5 6]]
[[1 4]
 [2 5]
 [3 6]]


In [51]:
# Tranpuesta de la transpuesta
print(q1.T.T)


[[1 2 3]
 [4 5 6]]


## Funciones de los Arrays

Numpy posee unas funciones universales de la clase array que permiten aplicar funciones matemáticas comunes a los elementos del array.
Funciones Matemáticas
* np.add(a1, a2): Suma dos arreglos
* np.subtract(a2, a1): Resta dos arreglos
* np.sqrt(a1): Obtiene la raíz cuadrada del arreglo
* np.power(a1,  2): Eleva a una potencia el arreglo
* np.sign(a1): Devuelve el signo del arreglo


In [52]:
#code
a1 = np.arange(0, 5)
a2 = np.array([8, -1, -9, 4, 2])
print('Array 1 = ', a1)
print('Array 2 = ', a2)

Array 1 =  [0 1 2 3 4]
Array 2 =  [ 8 -1 -9  4  2]


In [53]:
#Suma
asum = np.add(a1, a2)
print('Suma de Arreglos = ', asum)

Suma de Arreglos =  [ 8  0 -7  7  6]


In [54]:
#Resta
ares = np.subtract(a1,a2)
print('Resta de Arreglos = ', ares)

Resta de Arreglos =  [-8  2 11 -1  2]


In [56]:
#Raíz cuadrada a cada elemento
asqrt = np.sqrt(a1)
print('Raíz Cuadrada de Arreglos = ', asqrt)

Raíz Cuadrada de Arreglos =  [0.         1.         1.41421356 1.73205081 2.        ]


In [57]:
#Potencias
apow = np.power(a1, 4)
print('Potencia de Arreglos = ', apow)

Potencia de Arreglos =  [  0   1  16  81 256]


In [58]:
#Signos
asig = np.sign(a2)
print('Signos de los elementos del vector = ', asig)

Signos de los elementos del vector =  [ 1 -1 -1  1  1]


Numpy posee unas funciones universales de la clase array que permiten aplicar funciones matemáticas comunes a los elementos del array.
**Funciones Trigonométricas**

np.sin(a_1): Calcula el seno

np.tan(a_1): Calcula el coseno

np.deg2rad(a_1): Convierte de grados a radianes


In [60]:
#Code
print(np.sin(  np.rad2deg(a1)  ))

[0.         0.67952262 0.99706973 0.78348689 0.15254773]


Numpy posee unas funciones universales de la clase array que permiten aplicar funciones matemáticas comunes a los elementos del array.
**Funciones Comparativas**

np.maximum(a1, a2): Obtiene el máximo de dos arrays

np.equal(a1, a2): Compara los índices iguales

np.greater(a1, a2): Compara quien es más grande


In [61]:
#code
a1 = np.arange(0, 5)
a2 = np.array([8, -1, -9, 2, 4])
print('Array 1 = ', a1)
print('Array 2 = ', a2)

Array 1 =  [0 1 2 3 4]
Array 2 =  [ 8 -1 -9  2  4]


In [62]:
print(np.maximum(a1, a2))

[8 1 2 3 4]


Numpy posee unas funciones universales de la clase array que permiten aplicar funciones matemáticas comunes a los elementos del array.

**Funciones con Flotantes**

np.fabs(a3): Valor absoluto

np.ceil(a3): Redondeo al número más grande

np.floor(a3): Redondeo hacia el número mas bajo


In [ ]:
#Code
print('Array 2 = ', a2)
#Obtener valor absoluto
 

Numpy posee unas funciones universales de la clase array que permiten aplicar funciones matemáticas comunes a los elementos del array.

**Funciones Aleatorias**

np.random.rand(), np.random.rand(4), np.random.rand(4,2): Números aleatórios de decimales para array 1D y 2D

np.random.uniform(10, size=[2,2,2]): Números aleatorios para arreglos multidimensionales

np.random.randint(10): Números aleatorios entre 0 y N


In [64]:
#Code
print( np.random.rand(6, 6))

[[0.50202191 0.03097749 0.89561883 0.52560297 0.80634154 0.3392492 ]
 [0.05477907 0.33032789 0.55567527 0.11335589 0.53666042 0.02454961]
 [0.17225569 0.53034266 0.74023801 0.72195757 0.30134043 0.20639817]
 [0.06065049 0.65421043 0.14373316 0.62904883 0.2896649  0.61477733]
 [0.27127488 0.7858423  0.43261826 0.11438867 0.42569138 0.82209804]
 [0.76465995 0.94833067 0.00624875 0.88365187 0.28000256 0.69063217]]


In [65]:
print(np.random.uniform(0, 10, [2,2,3]))

[[[2.01291346 0.42441983 8.38500703]
  [1.21056714 9.43924283 2.2323194 ]]

 [[0.79734828 6.38826085 1.21493514]
  [2.51391136 9.19499931 8.57898714]]]


## Filtrado de Arrays

FILTROS BOOLEANOS: Son filtros que devuelven el estado de una condición

np.all( ): Devuelve verdadero si todos los elementos son verdaderos


np.any( ): Devuelve verdadero si al menos un elemento es verdaderos


In [70]:
## Filtrado de Arrays
a1 = np.random.randint(-1, 2, 10)
a2 = np.array([True, True, True, True])
print('Array 1 = ', a1)
print('Array 2 = ', a2)

Array 1 =  [ 0  0  1 -1 -1  0  1  1 -1  1]
Array 2 =  [ True  True  True  True]


In [72]:
np.all( a2 == True)

True

In [71]:
np.any(a2 == False)

False

FILTRO WHERE: Filtra un array a partir de una condición y un valor por defecto.


In [74]:
#code
a2 = np.random.uniform(0,5, size=[3,3]) #Arreglo multidimensional aleatorio
print(a2)
a2f = np.where( a2 >= 3, a2*2, -a2)
print(a2f)


[[2.16712771 4.85646193 3.0053108 ]
 [1.81604004 4.8739528  4.3678989 ]
 [4.33563037 4.75326823 3.79415187]]
[[-2.16712771  9.71292385  6.0106216 ]
 [-1.81604004  9.7479056   8.7357978 ]
 [ 8.67126075  9.50653647  7.58830374]]


FILTRO UNIQUE: Es un filtro empleado dentro de un array para poder encontrar los elementos únicos o simplemente elementos que no son repetidos.


In [19]:
#code
a1 = np.random.randint(-1, 2, 10)
print(a1)
#Filtro Unique
a1f = np.unique(a1)
print(a1f)


[ 0  1  1  0  0  1  0 -1 -1 -1]
[-1  0  1]


FILTRO IN1D: Retorna un array de una dimensión indicando si un determinado elemento existe dentro de un array.


## Módulos de NumPy

Algunos módulos de NumPy útiles para ingeniería son:

numpy.linag: Contiene todas las funciones para trabajar con álgebra lineal.

numpy.fft: Funciones para trabajar con la transformada de Fourier discreta.

https://numpy.org/doc/stable/reference/routines.linalg.html 
